Repository pharmaverse/aNCA, pull requests merged in 2024-10, with the labels that each got.

#34 Solved bug in Boxplot with oral data due to missing labels for AVAL (AVALU=NA)
  R/flexible_violinboxplot.R
  inst/shiny/tabs/outputs.R
Labels: high priority

#42 Documentation: add contributing md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT_SUGGESTION.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#35 Bug/settings and exclusions
  R/exportCDISC.R
  inst/shiny/tabs/data.R
  inst/shiny/tabs/nca.R
  inst/shiny/tabs/outputs.R
  inst/shiny/ui.R
Labels: high priority

#58 Enhancement/flexible axis boxplots
  R/flexible_violinboxplot.R
  inst/shiny/tabs/outputs.R
  inst/shiny/ui.R
Labels: enhancement
